USE ROLE ACCOUNTADMIN;
USE WAREHOUSE BERCA_WH;
USE DATABASE BERCA_TEST_DS;
USE SCHEMA GOLD;

-- 1. Buat Stage untuk menyimpan file YAML
-- 1. Create Stage to store YAML file
CREATE OR REPLACE STAGE AGENT_STAGE
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

